# ==========================================================
# 🧾 Loader YAML: cities_loader.yaml
# 🌱 Erstellt durch Auto-Loader
# ==========================================================
type: source
name: cities_loader
source_file: /data/shared/cities.csv
load_type: csv
project: prj-0002
node: node-0002
created_by: root
created_at: 2025-04-12T12:15:34+00:00
